#! /usr/bin/env python
import sys
import os
import sferes
print(sys.path[0])
sys.path.insert(0, sys.path[0] + '/waf_tools')

from waflib.Configure import conf

import dart
import corrade
import magnum
import magnum_integration
import magnum_plugins
import mcts
import robot_dart


def options(opt):
    opt.load('dart')
    opt.load('corrade')
    opt.load('magnum')
    opt.load('magnum_integration')
    opt.load('magnum_plugins')
    opt.load('mcts')
    opt.load('robot_dart')


@conf
def configure(conf):
    print('conf exp:')
    conf.load('dart')
    conf.load('corrade')
    conf.load('magnum')
    conf.load('magnum_integration')
    conf.load('magnum_plugins')
    conf.load('mcts')
    conf.load('robot_dart')

    conf.check_dart()
    conf.check_corrade(components='Utility PluginManager', required=False)
    conf.env['magnum_dep_libs'] = 'MeshTools Primitives Shaders SceneGraph GlfwApplication'
    if conf.env['DEST_OS'] == 'darwin':
        conf.env['magnum_dep_libs'] += ' WindowlessCglApplication'
    else:
        conf.env['magnum_dep_libs'] += ' WindowlessGlxApplication'
    conf.check_magnum(components=conf.env['magnum_dep_libs'], required=False)
    conf.check_magnum_plugins(components='AssimpImporter', required=False)
    conf.check_magnum_integration(components='Dart', required=False)
    if len(conf.env.INCLUDES_MagnumIntegration) > 0:
        conf.get_env()['BUILD_MAGNUM'] = True
        conf.env['magnum_libs'] = magnum.get_magnum_dependency_libs(
            conf, conf.env['magnum_dep_libs']) + magnum_integration.get_magnum_integration_dependency_libs(conf, 'Dart')
    conf.check_robot_dart()
    conf.check_mcts()

    print('done')


def build(bld):

    bld.program(features='cxx',
                source='main.cpp',
                includes='. ../../ /git/limbo/src/',
                uselib='ROBOTDART TBB BOOST EIGEN PTHREAD MPI DART ROBOT_DART MCTS',
                use='sferes2',
                target='example')

    bld.program(features='cxx',
                source='main.cpp',
                includes='. ../../ /git/limbo/src/',
                uselib=bld.env['magnum_libs'] +
                'ROBOTDART TBB BOOST EIGEN PTHREAD MPI DART ROBOT_DART DART_GRAPHIC MCTS',
                use='sferes2',
                defines=["GRAPHIC"],
                target='example_graphic')
